config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/', to: 'home#index'

  resources :questions do
    resources :answers, only: [:create]
  end
  resources :topics

  post 'question/:id/follow_topic', to: 'follower#follow_topic', as: :follow_topic
  post 'question/:id/follow_user', to: 'follower#follow_user', as: :follow_user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  # Association
	belongs_to :user
	belongs_to :question

	validates_presence_of :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  # Association
	belongs_to :user
	belongs_to :topic
	has_many :answers, dependent: :destroy

	validates_presence_of :name
end

app/models/topic.rb
class Topic < ApplicationRecord
	# Association
  has_many :topic_followers
  has_many :users, through: :topic_followers
	has_many :questions, dependent: :destroy

	validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/topic_follower.rb
class TopicFollower < ApplicationRecord
  # Association
  belongs_to :user
  belongs_to :topic

  validates :topic, uniqueness: { scope: :user, message: "Already following" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  has_many :user_followers
  has_many :following, through: :user_followers, source: :follower

  has_many :topic_followers
  has_many :topics, through: :topic_followers
end

app/models/user_follower.rb
class UserFollower < ApplicationRecord
  # Association
  belongs_to :user
  belongs_to :follower, class_name: 'User'

  validates :user, uniqueness: { scope: :follower, message: "Already following" }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_question

  def create
    # Create answer for question
    answer = @question.answers.new(answers_params.merge(user_id: current_user.id))
    if answer.save
      redirect_to question_path(@question), notice: 'Answer created sucessfully'
    else
      redirect_to question_path(@question), notice: 'Failed to create answer'
    end
  end

  private

  def find_question
    # Find question
    @question = Question.find_by(id: params[:question_id])
  end
  
  def answers_params
    params.require(:answer).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
 	def after_sign_in_path_for(resource)
	  '/'
	end

	def after_sign_out_path_for(resource)
		'/users/sign_in'
	end
end

app/controllers/follower_controller.rb
class FollowerController < ApplicationController
  before_action :find_question
  before_action :find_user, only: [:follow_user]

  def follow_user
    unless is_self_user?
      user = @question.user
      follower = @user.user_followers.create(follower_id: current_user.id)
      notice = follower.errors.present? ? follower.errors.full_messages.join(', ') : 'Followed sucessfully'
    else
      notice = 'Sorry! You cant follow youself'
    end
    redirect_to '/', notice: notice
  end

  def follow_topic
    follower = current_user.topic_followers.create(topic_id: @question.topic_id)
    redirect_to '/', notice: follower.errors.present? ? follower.errors.full_messages.join(', ') : 'Topic followed sucessfully'
  end

  private

  def find_user
    @user = @question.user
  end
  
  def find_question
    @question = Question.find(params[:id])
  end

  def is_self_user?
    current_user.id == @user.id
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
	def index
    # Get all questions
		@questions = Question.all
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def index
    # Get all questions
    @questions = current_user.questions
  end

  def new
    @question = Question.new
  end

  def create
    # Create question for current logged in user
    question = current_user.questions.new(question_params)
    if question.save
      redirect_to question_path(question), notice: 'Question created sucessfully'
    else
      redirect_to '/', notice: 'Failed to create question'
    end
  end

  def show
    # Get question
    @question = Question.find_by_id(params[:id])
    # Get answers for the question
    @answers = @question.answers
  end

  private

  def question_params
    params.require(:question).permit(:name, :topic_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def new
    @topic = Topic.new
  end

  def index
    @topics = Topic.all
  end

  def create
    # Create new topic
    topic = Topic.new(topic_params)
    if topic.save
      redirect_to '/', notice: 'Topic created sucessfully'
    else
      redirect_to '/', notice: 'Failed to create topic'
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follower_helper.rb
module FollowerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/home/index.html.erb
<% @questions.each do |question| %>
	<%= link_to "#{question.name}", question_url(question.id), class: 'question' %>
	<%= link_to "follow #{question.topic.name}", "#{request.base_url}/question/#{question.id}/follow_topic", method: :post, class: 'follow_topic' %>
	<%= link_to "follow #{question.user.email}", follow_user_url(question.id), method: :post, class: 'follow_user' %><br>
<% end %>
<%= link_to 'create question', new_question_path %>
<%= link_to 'create topic', new_topic_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <style>
      body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
      }

      .topnav {
        overflow: hidden;
        background-color: #333;
      }

      .topnav a {
        float: left;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
      }

      .topnav a:hover {
        background-color: #ddd;
        color: black;
      }

      .topnav a.active {
        background-color: #4CAF50;
        color: white;
      }
      </style>
  </head>

  <body>
    <div class="topnav">
      <a class="active" href="/">Home</a>
      <% unless current_user.present? %>
        <%= link_to 'sign_in', new_user_session_url %>
      <%else%>
        <%= link_to 'sign_out', destroy_user_session_url, method: :delete%>
      <%end%>
    </div>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <%@errors ||= []%>
        <% if @errors.any? %>
          <% @errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/new.html.erb
<h3>Create Question</h3>
<%= form_for @question do |f| %>
	<%= f.label 'Select topic' %>
	<%= f.select :topic_id, options_for_select(Topic.all.map{|t| [t.name, t.id] })%>
	<%= f.label 'Question' %>
	<%= f.text_field :name %><br>
	<%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<h3><%= @question.name %></h3>
<% @answers.each do |answer| %>
	<p class='answer'><%= answer.name%></p>
<% end %>

<h3>Submit answer</h3>
<%= form_for :answer, url: question_answers_path(@question) do |f| %>
	<%= f.label 'Name' %>
	<%= f.text_area :name %><br>
	<%= f.submit %>
<% end %>

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
	<p><%= topic.name %>
<% end %>

app/views/topics/new.html.erb
<h3>Create Topic</h3>
<%= form_for @topic do |f| %>
	<%= f.label 'Topic' %>
	<%= f.text_field :name %><br>
	<%= f.submit %>
<% end %>